global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'monitor-agent'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'monitor-agent'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          service: 'otel-collector'

  - job_name: 'otel-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'otel-metrics'
